packages:
  - packages/*
  - demo

catalog:
  '@antfu/eslint-config': ^3.7.3
  '@arms/rum-browser': ^0.0.37
  '@codingame/esbuild-import-meta-url-plugin': ^1.0.3
  '@codingame/monaco-vscode-api': ^20.2.1
  '@codingame/monaco-vscode-base-service-override': ^20.2.1
  '@codingame/monaco-vscode-editor-api': ^20.2.1
  '@codingame/monaco-vscode-editor-service-override': ^20.2.1
  '@codingame/monaco-vscode-extensions-service-override': ^20.2.1
  '@codingame/monaco-vscode-languages-service-override': ^20.2.1
  '@codingame/monaco-vscode-layout-service-override': ^20.2.1
  '@codingame/monaco-vscode-python-default-extension': ^20.2.1
  '@codingame/monaco-vscode-standalone-languages': ^20.2.1
  '@codingame/monaco-vscode-storage-service-override': ^20.2.1
  '@codingame/monaco-vscode-textmate-service-override': ^20.2.1
  '@codingame/monaco-vscode-theme-defaults-default-extension': ^20.2.1
  '@codingame/monaco-vscode-theme-service-override': ^20.2.1
  '@commitlint/cli': ^19.2.1
  '@commitlint/config-conventional': ^19.1.0
  '@dagrejs/dagre': ^1.1.3
  '@floating-ui/vue': ^1.1.6
  '@iconify/json': ^2.2.367
  '@iconify/utils': ^2.1.25
  '@iconify/vue': ^4.1.1
  '@monaco-editor/loader': ^1.4.0
  '@prosopo/vite-plugin-watch-workspace': ^2.6.4
  '@shikijs/monaco': ^2.3.2
  '@shikijs/types': ^2.4.2
  '@shikijs/vscode-textmate': ^10.0.2
  '@tiptap/core': ^2.11.5
  '@tiptap/extension-blockquote': ^2.11.5
  '@tiptap/extension-bold': ^2.11.5
  '@tiptap/extension-bubble-menu': ^2.11.5
  '@tiptap/extension-bullet-list': ^2.11.5
  '@tiptap/extension-character-count': ^2.11.5
  '@tiptap/extension-code': ^2.11.5
  '@tiptap/extension-code-block': ^2.11.5
  '@tiptap/extension-color': ^2.11.5
  '@tiptap/extension-document': ^2.11.5
  '@tiptap/extension-dropcursor': ^2.11.5
  '@tiptap/extension-gapcursor': ^2.11.5
  '@tiptap/extension-hard-break': ^2.11.5
  '@tiptap/extension-heading': ^2.11.5
  '@tiptap/extension-highlight': ^2.11.5
  '@tiptap/extension-history': ^2.11.5
  '@tiptap/extension-horizontal-rule': ^2.11.5
  '@tiptap/extension-image': ^2.11.5
  '@tiptap/extension-italic': ^2.11.5
  '@tiptap/extension-link': ^2.11.5
  '@tiptap/extension-list-item': ^2.11.5
  '@tiptap/extension-ordered-list': ^2.11.5
  '@tiptap/extension-paragraph': ^2.11.5
  '@tiptap/extension-placeholder': ^2.11.5
  '@tiptap/extension-strike': ^2.11.5
  '@tiptap/extension-table': ^2.11.5
  '@tiptap/extension-table-cell': ^2.11.5
  '@tiptap/extension-table-header': ^2.11.5
  '@tiptap/extension-table-row': ^2.11.5
  '@tiptap/extension-task-item': ^2.11.5
  '@tiptap/extension-task-list': ^2.11.5
  '@tiptap/extension-text': ^2.11.5
  '@tiptap/extension-text-align': ^2.11.5
  '@tiptap/extension-text-style': ^2.11.5
  '@tiptap/extension-underline': ^2.11.5
  '@tiptap/pm': ^2.11.5
  '@tiptap/suggestion': ^2.11.5
  '@tiptap/vue-3': ^2.25.0
  '@types/big.js': ^6.2.2
  '@types/diff': ^7.0.1
  '@types/dompurify': ^3.0.5
  '@types/js-yaml': ^4.0.9
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.3.0
  '@types/qs': ^6.9.11
  '@types/sortablejs': ^1.15.8
  '@types/spark-md5': ^3.0.4
  '@types/web': 0.0.259
  '@unocss/core': ^66.4.2
  '@unocss/eslint-plugin': ^66.4.2
  '@unocss/preset-icons': ^66.4.2
  '@unocss/preset-uno': ^66.4.2
  '@unocss/transformer-directives': ^66.4.2
  '@unocss/transformer-variant-group': ^66.4.2
  '@unocss/vite': ^66.4.2
  '@vite-pwa/vitepress': ^1.0.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.0.1
  '@vue-flow/core': ^1.39.1
  '@vue/compiler-sfc': ^3.4.15
  '@vueuse/core': ^13.5.0
  '@vueuse/router': ^10.11.0
  '@webcontainer/api': 1.5.1-internal.9
  '@xterm/addon-fit': ^0.10.0
  '@xterm/addon-web-links': ^0.11.0
  '@xterm/addon-webgl': ^0.18.0
  '@xterm/xterm': ^5.5.0
  ajv: ^8.12.0
  ajv-formats: ^2.1.1
  ansi_up: ^6.0.6
  async-validator: ^4.2.5
  axios: ^1.6.5
  axios-retry: ^4.5.0
  big.js: ^6.2.1
  chart.js: ^4.4.6
  colord: ^2.9.3
  comlink: ^4.4.2
  cross-env: ^7.0.3
  csv-parse: ^5.5.6
  dayjs: ^1.11.13
  diff: ^8.0.2
  dompurify: ^3.2.6
  eslint: ^9.12.0
  eslint-config-prettier: ^9.1.0
  fflate: ^0.8.2
  github-markdown-css: ^5.8.1
  handlebars: ^4.7.8
  html2pdf.js: ^0.9.3
  husky: ^9.1.7
  js-yaml: ^4.1.0
  katex: ^0.16.28
  lint-staged: ^15.2.10
  localforage: ^1.10.0
  lodash-es: ^4.17.21
  markdown-it-mathjax3: ^4.3.2
  mermaid: ^11.10.1
  minisearch: ^7.1.1
  monaco-editor: ^0.52.2
  monaco-editor-core: ^0.52.2
  monaco-languageclient: ^9.11.0
  naive-ui: 2.41.0
  nanoid: ^5.0.4
  p-retry: ^6.2.1
  pdfjs-dist: ^4.4.168
  pinia: 3.0.3
  pinia-plugin-persistedstate: ^4.1.1
  postcss: ^8.4.33
  postcss-rtlcss: ^5.7.1
  prettier: ^3.3.3
  prosemirror-tables: 1.6.4
  proxy-agent: ^6.4.0
  pyodide: ^0.28.0
  qs: ^6.11.2
  remark-shiki-twoslash: ^3.1.3
  sass: ^1.90.0
  shiki: ^2.3.2
  shiki-twoslash: ^3.1.2
  smol-toml: 1.3.4
  sortablejs: ^1.15.6
  spark-md5: ^3.0.2
  tiptap-markdown: ^0.8.10
  treemate: ^0.3.11
  typescript: 5.8.3
  unocss: ^0.58.3
  unplugin-auto-import: ^0.17.3
  unplugin-icons: ^22.2.0
  unplugin-vue-components: ^0.27.4
  vite: ^7.1.3
  vite-plugin-inspect: ^0.8.9
  vite-plugin-mkcert: ^1.17.8
  vite-plugin-progress: ^0.0.7
  vite-plugin-vue-devtools: ^8.0.0
  vite-tsconfig-paths: ^5.1.4
  vitepress: 2.0.0-alpha.8
  vitepress-plugin-group-icons: ^1.6.1
  vscode-jsonrpc: ^8.2.1
  vscode-languageclient: ^9.0.1
  vue: ^3.5.17
  vue-chartjs: ^5.3.2
  vue-i18n: ^9.9.0
  vue-router: ^4.2.5
  vue-tsc: ^3.0.6
  workbox-cacheable-response: ^7.3.0
  workbox-core: ^7.3.0
  workbox-expiration: ^7.3.0
  workbox-precaching: ^7.3.0
  workbox-routing: ^7.3.0
  workbox-strategies: ^7.3.0
